<template>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        <img
          width="64px"
          height="64px"
          :src="msg.user.avatar"
          :style="styleObj"
        />
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ msg.user.display_name }}</strong>
          <small>@{{ msg.user.username }}</small>
          <!-- append-to-body -->
          <b-tooltip :label="longDateTime(msg.timestamp)" type="is-dark">
            <small
              class="has-text-grey"
              style="text-decoration:none"
              onmouseover="style='text-decoration:underline'"
              onmouseout="style='text-decoration:none'"
              >{{ shortDateTime(msg.timestamp) }}</small
            >
          </b-tooltip>
          <br />
          {{ msg.text }}
        </p>
      </div>
    </div>
  </article>
</template>

<script>
import { mapGetters } from "vuex";
import moment from "moment";

export default {
  props: {
    msg: {
      type: Object,
      required: true
    }
  },
  mounted() {
    // Automatically scroll to element when created
    this.$el.scrollIntoView();
  },
  methods: {
    /**
     * All timestamps are UTC, but when returned from server
     * they lack 'Z' whereas when generated by JavaScript they have
     */
    isoify(timestamp) {
      if (timestamp.slice(-1) != "Z") {
        timestamp = timestamp + "Z";
      }
      return timestamp;
    },
    shortDateTime(timestamp) {
      timestamp = this.isoify(timestamp);
      return moment(timestamp, moment.ISO_8601).format("h:mm A");
    },
    longDateTime(timestamp) {
      timestamp = this.isoify(timestamp);
      return moment(timestamp, moment.ISO_8601).format(
        "MMMM Do YYYY, h:mm:ss a"
      );
    }
  },
  computed: {
    ...mapGetters(["loggedInUser"]),
    isOwnMessage: function() {
      return this.msg.user_id === this.loggedInUser.id;
    },
    styleObj: function() {
      return {
        borderRadius: "20%",
        border: this.isOwnMessage ? "2px solid #7957d5" : "1px solid grey"
      };
    }
  }
};
</script>
