<template>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        <img width="64px" height="64px" :src="user.avatar" :style="styleObj" />
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ user.display_name }}</strong>
          <small>@{{ user.username }}</small>
          <b-tooltip :label="longDateTime(msg.timestamp)" type="is-dark">
            <small
              class="has-text-grey"
              style="text-decoration:none"
              onmouseover="style='text-decoration:underline'"
              onmouseout="style='text-decoration:none'"
              >{{ shortDateTime(msg.timestamp) }}</small
            >
          </b-tooltip>
          <br />
          {{ msg.text }}
        </p>
      </div>
    </div>
  </article>
</template>

<script>
import { mapGetters } from "vuex";
import moment from "moment";

/**
 * All timestamps are UTC, but when returned from server
 * they lack 'Z' whereas when generated by JavaScript they have
 */
function isoify(timestamp) {
  if (timestamp.slice(-1) != "Z") {
    timestamp = timestamp + "Z";
  }
  return timestamp;
}

/**
 * This component is for displaying a single message in the chat.
 */
export default {
  props: {
    msg: {
      type: Object,
      required: true
    },
    user: {
      type: Object,
      required: true
    }
  },
  mounted() {
    // Automatically scroll to element when created
    this.$el.scrollIntoView();
  },
  methods: {
    shortDateTime(timestamp) {
      timestamp = isoify(timestamp);
      return moment(timestamp, moment.ISO_8601).format("h:mm A");
    },
    longDateTime(timestamp) {
      timestamp = isoify(timestamp);
      return moment(timestamp, moment.ISO_8601).format(
        "MMMM Do YYYY, h:mm:ss a"
      );
    }
  },
  computed: {
    ...mapGetters(["loggedInUser"]),
    isOwnMessage: function() {
      return this.msg.user_id === this.loggedInUser.id;
    },
    styleObj: function() {
      return {
        borderRadius: "20%"
      };
    }
  }
};
</script>
